### ISSUE TITLE
Text Editor slowdown on long keypressdown or when there is too much text (200+ chars)

### ISSUE THREAD

**Issue by vFujin** [vFujin/HearthLounge#83]
I assume it's rendering issue by passing editorState state to parent node which re-renders whole div instead of textarea/editor area. 

Though need to get that value to be passed later on on submit.

**Comment by xNehel** [comment]
_.debouncer should fix it

**Comment by vFujin** [comment]
Changing create-deck actions to separate action creators folder slow down the textarea again, though debounce is working properly.

**Comment by vFujin** [comment]
Switched accidentally function from declared function to expressed which screwed the performance.
